### ISSUE TITLE
New travis builds are failing since v0.8.1

### ISSUE THREAD

**Issue by DieterReuter** [hypriot/os-rootfs#26]
The build for v0.8.2 is running fine with all tests passing. But the file upload to GH releases is still failing.

@Govinda-Fichtner, are there any missing changes from v0.8.1 which are not committed or merged?
The release files from v0.8.1 seems to be manually uploaded.

**Comment by Govinda-Fichtner** [comment]
No. They were uploaded by Travis.
Am 09.04.2016 13:39 schrieb "Dieter Reuter" <notifications@github.com>:

**Comment by StefanScherer** [comment]
Maybe a flaky build in Travis. Try to rebuild or just release v0.8.3 to try again.

**Comment by DieterReuter** [comment]
No, there are some things missing in renaming the new build artefacts. @firecyberice is already fixing it. Maybe GH has lost a commit or two accidentally...

**Comment by DieterReuter** [comment]
Fixed by #27.

**Comment by Govinda-Fichtner** [comment]
@DieterReuter @StefanScherer @firecyberice  Here is the build with the correct filename that was having all tests green: https://travis-ci.org/hypriot/os-rootfs/builds/121417256#L5323

It is the same build that automatically deployed the result to Github releases.

The commit which belongs to it shows clearly how the VARIANT part was added to the filename.
So it is clearly exactly as I told you at the phone, Dieter. I little research yourself would how shown you that easily.

I do not know what you guys did afterwards...
