### ISSUE TITLE
Image contains pregenerated SSH host keys

### ISSUE THREAD

**Issue by djmaze** [hypriot/os-rootfs#3]
Each host should have its own set of SSH keys. As of now, the SSH keys are generated during the install of the package `openssh-server`. That means the keys end up in the image.

For a clean solution, we should probably remove the pregenerated keys during build of the rootfs. Additionally, we have to make sure the keys are [regenerated](https://wiki.debian.org/SSH#Regenerating_host_keys) on first boot.

**Comment by StefanScherer** [comment]
@djmaze Very good point! So a `rm /etc/ssh/ssh_host_*` should be done here and a test should proof this that the files no longer exist.

**Comment by djmaze** [comment]
There is no need to do the key regeneration on a per-device basis. And the aim should be to do as much as possible inside the (device-independent) rootfs, right? So I think we need to add a first-time boot service here which runs the `dpkg-reconfigure openssh-server`, as opposed to duplicating this effort in every device-specific builder script (see https://github.com/hypriot/image-builder-rpi/issues/9).

We also need to figure out a clean way to run a one-time service on bootup. I am not very comfortable with the fact that the root partition (at least in the C1 image) is resized on every boot. The easiest way would probably be to just append an entry to an env file after the first run.

**Comment by Govinda-Fichtner** [comment]
@djmaze @StefanScherer I created a generic first-boot service in PR #7 to address this.
