### ISSUE TITLE
Root prompt should be # not $

### ISSUE THREAD

**Issue by rcludwick** [hypriot/os-rootfs#49]
Nit picky I know, but for those of us that live on the linux command line, the prompt for the root user after doing sudo -i should be # not $.

**Comment by glensc** [comment]
from [bash manual](https://www.gnu.org/software/bash/manual/bashref.html#Controlling-the-Prompt):

> \$
> If the effective uid is `0`, `#`, otherwise `$`.

so, `PS1` needs to contain `\$` literally, if inside double quotes as `PROMPTCHAR="\\\$"`
