### ISSUE TITLE
Debian stretch port not working with errors

### ISSUE THREAD

**Issue by gdeverlant** [hypriot/os-rootfs#51]
Tried to adapt the image version for Debian Stretch 9.0 at https://github.com/gdeverlant/os-rootfs/tree/stretch.

OS: Windows 10
VM: VirtualBox with Debian Stretch 9.0

I'm getting this error

```
I: Unpacking libperl5.24:arm64...
I: Unpacking perl...
I: Unpacking perl-modules-5.24...
I: Unpacking pinentry-curses...
I: Unpacking libpopt0:arm64...
I: Unpacking libprocps6:arm64...
I: Unpacking procps...
I: Unpacking libreadline7:arm64...
I: Unpacking readline-common...
I: Unpacking rsyslog...
I: Unpacking librtmp1:arm64...
I: Unpacking libslang2:arm64...
I: Unpacking libsqlite3-0:arm64...
I: Unpacking sudo...
I: Unpacking libpam-systemd:arm64...
I: Unpacking systemd...
I: Unpacking udev...
I: Unpacking systemd-shim...
I: Unpacking tasksel...
I: Unpacking tasksel-data...
I: Unpacking libwrap0:arm64...
I: Unpacking ucf...
I: Unpacking usbutils...
I: Unpacking vim-common...
I: Unpacking vim-tiny...
I: Unpacking xxd...
I: Unpacking wget...
I: Unpacking libxapian30:arm64...
W: Failure while installing base packages.  This will be re-attempted up to five times.
W: See //debootstrap/debootstrap.log for details (possibly the package /var/cache/apt/archives/init_1.48_arm64.deb is at fault)
W: Failure while installing base packages.  This will be re-attempted up to five times.
W: See //debootstrap/debootstrap.log for details (possibly the package /var/cache/apt/archives/init_1.48_arm64.deb is at fault)
W: Failure while installing base packages.  This will be re-attempted up to five times.
W: See //debootstrap/debootstrap.log for details (possibly the package /var/cache/apt/archives/init_1.48_arm64.deb is at fault)
W: Failure while installing base packages.  This will be re-attempted up to five times.
W: See //debootstrap/debootstrap.log for details (possibly the package /var/cache/apt/archives/init_1.48_arm64.deb is at fault)
W: Failure while installing base packages.  This will be re-attempted up to five times.
W: See //debootstrap/debootstrap.log for details (possibly the package /var/cache/apt/archives/init_1.48_arm64.deb is at fault)
Makefile:17: recipe for target 'arm64-debian' failed
make: *** [arm64-debian] Error 1
```

**Comment by neta540** [comment]
You need to use a newer debootstrap. the base docker is based on hypriot/image-builder which is in turn based on debian:jessie  once you use a newer debootstrap, from debian:stretch, it will work.

**Comment by gdeverlant** [comment]
Do you have any idea where to change this (which files) in my fork so that the new debootstrap is used during the build process?

**Comment by neta540** [comment]
Yes, you need to modify the Dockerfile to base from an image other than hypriot/image-builder. debian:stretch will be good with RUN commands to fetch debootstrap and all the necessary dependecies for your build.sh script.
I used:

FROM debian:stretch

RUN apt-get update && apt-get install -y \
    debootstrap \
    wget \
    ruby \
    ruby-dev \
    binfmt-support \
    qemu \
    qemu-user-static \
    --no-install-recommends && \
    rm -rf /var/lib/apt/lists/*

COPY builder /builder/
CMD /builder/build.sh

for my usage.

Another option is to modify build.sh so that before calling debootstrap at
https://github.com/hypriot/os-rootfs/blob/65fd2b38395cbcdac997dca2999b0c05eec1f747/builder/build.sh#L59
you will add commands to change with sed the apt sources from jessie to stretch , then run apt-get update and install a newer debootstrap before calling it. I haven't tried it but it should work.

**Comment by firecyberice** [comment]
The tag v1.2.4 is the first version with stretch.
