### ISSUE TITLE
pirate has no input group

### ISSUE THREAD

**Issue by glensc** [hypriot/os-rootfs#60]
as a result, installing kodi leaves one without keyboard and mouse.

[quick fix](https://raspberrypi.stackexchange.com/a/27104):
```
sudo usermod -a -G input pirate
```

but i think it should be done by default, as with other groups

**Comment by firecyberice** [comment]
The default user is removed from the rootfs. If you need groups add them here please: https://github.com/hypriot/image-builder-rpi/blob/master/builder/files/boot/user-data#L20

**Comment by glensc** [comment]
yes. thanks. i could not find where user "pirate" was created, and then sleep time arrived.
