### ISSUE TITLE
Missing Packages less and dirmngr

### ISSUE THREAD

**Issue by ecliptik** [hypriot/os-rootfs#64]
When running the latest HypriotOS image it seems some packages are missing from newer builds of os-rootfs, specifically I noticed `less` and `dirmngr`. This is causing an issue (https://github.com/DieterReuter/image-builder-rpi64/issues/56) when trying to add GPG keys with `cloud-init`.

Not sure if there are other packages missing as well, but these two I noticed right away when I re-flashed the latest HypriotOS [v20180107-184643](https://github.com/DieterReuter/image-builder-rpi64/releases/tag/v20180107-184643) which uses [v1.2.5](https://github.com/hypriot/os-rootfs/releases/tag/v1.2.5) in commit https://github.com/DieterReuter/image-builder-rpi64/commit/6d0ef7451bb26bf60298a740d979c1bee5c9db5c

**Comment by firecyberice** [comment]
debootstrap does not resolve recommends https://lists.debian.org/debian-user/2017/01/msg00921.html

**Comment by ecliptik** [comment]
@firecyberice apparently this was filed as a bug last year, but not moved to a dep due to `gpg` "functioning properly without network support". In order to use network features (such as adding keys from a keyserver) this package is required.

The bug is discussed here,
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=845720

I'm testing out a debian-arm64 image where `dirmngr` is added to `DEFAULT_PACKAGES_INCLUDE` and see if `cloud-init` works properly again.

**Comment by DieterReuter** [comment]
As noted in https://github.com/DieterReuter/image-builder-rpi64/issues/56 I think we should add these dependencies while installing `cloud-init`.
