### ISSUE TITLE
Missing release file for debian stretch repo

### ISSUE THREAD

**Issue by Darren-Hill** [hypriot/os-rootfs#68]
Not sure if this is the right branch to raise this on, so apologies if it's not.

Trying to apt-get update on my HypriotOS Pi, and getting the following:

$ sudo apt-get update
Hit:1 http://raspbian.raspberrypi.org/raspbian stretch InRelease
Hit:2 http://archive.raspberrypi.org/debian stretch InRelease
Hit:3 https://download.docker.com/linux/raspbian stretch InRelease
Ign:5 https://packagecloud.io/Hypriot/Schatzkiste/debian stretch InRelease
Err:6 https://packagecloud.io/Hypriot/Schatzkiste/debian stretch Release
  404  Not Found
Hit:4 https://packagecloud.io/Hypriot/rpi/debian stretch InRelease
Reading package lists... Done
E: The repository 'https://packagecloud.io/Hypriot/Schatzkiste/debian stretch Release' does no longer have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.

Is something under update at the server end, or has something gone wrong? The release file seems to be AWOL?

**Comment by firecyberice** [comment]
Please have a look at: https://github.com/hypriot/image-builder-rpi/pull/234
In the last version the Schatzkiste Repo is removed.
