### ISSUE TITLE
Introduce shellcheck?

### ISSUE THREAD

**Issue by StefanScherer** [hypriot/os-rootfs#8]
To improve code quality in our shell scripts the idea arised if we should introduce http://www.shellcheck.net and check all scripts in the Travis build.

Build a PR for that and let's see and discuss how to step further.

**Comment by StefanScherer** [comment]
Just installed

```
brew install shellcheck
apm install linter
apm install linter-shellcheck
```

See also https://github.com/atom-community/linter

**Comment by StefanScherer** [comment]
Cool. Both Atom and `shellcheck` found the problem of #16.

```
$ shellcheck builder/files/usr/local/bin/hypriot-firstboot 

In builder/files/usr/local/bin/hypriot-firstboot line 4:
source /etc/firstboot.d/*
^-- SC1090: Can't follow non-constant source. Use a directive to specify location.
```

![bildschirmfoto 2016-02-11 um 22 24 31](https://cloud.githubusercontent.com/assets/207759/12991151/3c766dc8-d10e-11e5-8ec5-ef03d01c8e8d.png)

@DieterReuter I love it!

**Comment by MathiasRenner** [comment]
Cool!

**Comment by StefanScherer** [comment]
Added in #18, waiting for Travis results... ;-)
